name: Perform SAST + DAST checks on PRs

on:
    push:
        branches: [master, main]

jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            - name: Install python and pip
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install bandit
              run: |
                  python -m pip install --upgrade pip
                  pip install bandit

            - name: Run bandit against the source
              run: |
                  ls -la
                  bandit --exclude ./env/ . -r -f json --output bandit-results.json
                  cat bandit-results.json
