name: Perform SAST + DAST checks on PRs

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            - name: Install python and pip
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install bandit and slack modules
              run: |
                  python -m pip install --upgrade pip
                  pip install bandit slack_sdk

            - name: Run bandit against the source of application
              run: |
                  bandit --exclude ./.github/ . -r -f json --output bandit-output.json --exit-zero
                  ls -la
                  cat bandit-output.json

            - name: Import secrets from hashicorp and set as environmental variables
              uses: hashicorp/vault-action@v2.3.1
              with:
                  url: ${{ secrets.VAULT_URL }}
                  method: token
                  token: ${{ secrets.VAULT_TOKEN }}
                  namespace: ns1
                  secrets: |
                      /cubbyhole/slack/slack_secrets slack_bot_token | SLACK_BOT_TOKEN;
                      /cubbyhole/slack/slack_secrets slack_channel_id | SLACK_CHANNEL_ID

            - name: Parse bandit output and post on slack using hashicorp exported secrets
              run: python .github/parse-bandit-results.py
            #   env:
            #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            #       SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
